config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'static_pages#home'
resources :corsairs 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController

  def new
    @moussaillon = Corsair.new
  end

  def create
    @moussaillon = Corsair.new(params[:corsair])  #(corsair_params)
    @moussaillon.first_name = params[:first_name]
    @moussaillon.age = params[:age]
    @moussaillon.save
    p params

    redirect_to @moussaillon

  end

  def show
    @moussaillon = Corsair.find(params[:id])
  end

  def edit
    @moussaillon = Corsair.find(params[:id])
  end

  def update
    @moussaillon = Corsair.find(params[:id])

    if @moussaillon.update(corsair_params) #(corsair_params)
      redirect_to @moussaillon
    else
      render 'edit'
    end
  end

  def index
    @moussaillons = Corsair.all
  end

  def destroy
    @corsair = Corsair.find(params[:id])
    @corsair.destroy
    redirect_to corsairs_path
  end

  # private

  def corsair_params
    params.require(:corsair).permit(:first_name, :age) # :likeness, :bio)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/dit.html.erb
<br /><br />
<h1>Modification de vos informations</h1>
<br /><br />

<p>
 <%= form_tag corsair_path(@moussaillon), method: :put do %>
 <h3>Name</h><br />
  <!-- <%= label_tag 'first_name', 'Nom' %> -->
  <%= text_field_tag 'first_name' %>
</p>

<p>
  <h>Age</h><br />
  <!-- <%= label_tag 'age', 'Age' %> -->
  <%= text_field_tag 'age' %>
</p>


   <%= submit_tag "Mettre à jour"%>
 <% end %>

 <%= link_to 'Back', corsairs_path %>

app/views/corsairs/edit.html.erb
<br /><br />

<h1>Edition du Moussaillon</h1>

<%= form_with(model: @moussaillon) do |form| %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>
<%= link_to 'Back', corsairs_path %>

app/views/corsairs/index.html.erb
<br /><br />

<h1>Liste des moussaillons</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th colspan="3"></th>

  </tr>

  <% @moussaillons.each do |moussaillon| %>
  <tr>
    <td><%= moussaillon.first_name %></td>
    <td><%= moussaillon.age %></td>
    <td><%= link_to("Voir", corsair_path(moussaillon))%></td>
    <td><%= link_to("Edit", edit_corsair_path(moussaillon))%></td>
    <td><%= link_to 'Suppr', corsair_path(moussaillon),
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
  </tr>

  <% end %>
</table>

<br /><br />
<%= link_to "Enregistre-toi !", new_corsair_path, class: "btn btn-lg btn-primary" %>

app/views/corsairs/new.html.erb
<br /><br />
<h1>Enregistrement d'un nouveau Moussaillon</h1>
<br /><br />

<p>
 <%= form_tag (corsairs_path) do %>
 <h3>Name</h><br />
  <!-- <%= label_tag 'first_name', 'Nom' %> -->
  <%= text_field_tag 'first_name' %>
</p>

<p>
  <h>Age</h><br />
  <!-- <%= label_tag 'age', 'Age' %> -->
  <%= text_field_tag 'age' %>
</p>


   <%= submit_tag "Sign Up"%>
 <% end %>

app/views/corsairs/show.html.erb
<br /><br />

<h1>Enregistrement effectué ! </h1>
<h3>Vous avez soumi les informations ci dessous</h3>
<h4>Nom : <%= @moussaillon.first_name %></h4>
<h4>Age : <%= @moussaillon.age %></h4>

<%= link_to 'Back', corsairs_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '#' %></li>
        <li><%= link_to "Index des moussaillons",   '#' %></li>
        <li><%= link_to "Nouveau moussaillon", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpMoussaillons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Accueil", root_path %></li>
            <li><%= link_to "Index des moussaillons", corsairs_path %></li>
            <li><%= link_to "Nouveau moussaillon", new_corsair_path %></li>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
  </body>

</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", new_corsair_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to "Accèder à la liste des moussaillons", corsairs_path %>